[package]
name = "dbcppp_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbcppp_rs_sys = { path = "../rs_sys" }